### ISSUE TITLE
Вопрос о формате 

### ISSUE THREAD

**Issue by exrector** [noyatsenko/freelib-mac-2#1]
Я извиняюсь, конечно. Но раз вы сделали этот форк, значит у вас была также задача, что и у меня - база Флибусты на маке. Вы вероятно, в теме больше меня, поэтому спрошу. У меня киндл ридер и базу хочется в epub. А нашел я на трекерах только fb2. Качать fb2 и конвертировать внутри feeling, я правильно понимаю? Или есть на просторах вся база в формате EPUB? Спасибо.

**Comment by noyatsenko** [comment]
Добрый день!

Негласным стандартом хранения книг является fb2.zip -- поэтому epub базы я просто не встречал.

В форке нативно встроен kindlegen, который занимается конвертацией между форматами при экспорте книги. Бинарник выпущен Амазоном в x64 -- поэтому для его работы потребуется яблочная Розетта.
```
softwareupdate --install-rosetta --agree-to-license
```

Можете отдельно использовать kindlegen для переконвертации вне freelib хоть всей библиотеки, вот его справка по использованию:
```
*************************************************************
 Amazon kindlegen(MAC OSX) V2.9 build 0000-kdevbld 
 A command line e-book compiler 
 Copyright Amazon.com and its Affiliates 2015 
*************************************************************

Usage : kindlegen [filename.opf/.htm/.html/.epub/.zip or directory] [-c0 or -c1 or c2] [-verbose] [-western] [-o <file name>] 
Note: 
   zip formats are supported for XMDF and FB2 sources
   directory formats are supported for XMDF sources
Options: 
   -c0: no compression 
   -c1: standard DOC compression 
   -c2: Kindle huffdic compression 
   -o <file name>: Specifies the output file name. Output file will be created in the same directory as that of input file. <file name> should not contain directory path. 
   -verbose: provides more information during ebook conversion 
   -western: force build of Windows-1252 book 
   -releasenotes: display release notes 
   -gif: images are converted to GIF format (no JPEG in the book) 
   -locale <locale option> : To display messages in selected language 
      en: English
      de: German
      fr: French
      it: Italian
      es: Spanish
      zh: Chinese
      ja: Japanese
      pt: Portuguese
      ru: Russian
      nl: Dutch
```
