### ISSUE TITLE
Ошибка при компиляции под MacOS Sequoia 15.0

### ISSUE THREAD

**Issue by alldevit** [noyatsenko/freelib-mac-2#2]
На этапе компиляции, после ввода команды `cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/Applications/freelib.app .. && cmake --build . -j4` возникает ошибка:

```
CMake Error at /opt/homebrew/Cellar/qt/6.7.2/lib/cmake/Qt6/QtPublicWalkLibsHelpers.cmake:259 (message):
  The Core5Compat target is mentioned as a dependency for QuaZip::QuaZip, but
  not declared.
Call Stack (most recent call first):
  /opt/homebrew/Cellar/qt/6.7.2/lib/cmake/Qt6/QtPublicWalkLibsHelpers.cmake:311 (__qt_internal_walk_libs)
  /opt/homebrew/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:651 (__qt_internal_collect_all_target_dependencies)
  /opt/homebrew/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:774 (_qt_internal_finalize_executable)
  /opt/homebrew/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:877 (qt6_finalize_target)
  freeLib/src/CMakeLists.txt:145 (qt_finalize_executable)
  ```

**Comment by noyatsenko** [comment]
QT6 со своими особенностями включая проблемы деплоя. В данном случае похоже с QuaZip https://github.com/stachenov/quazip

Когда будет Секвойя -- проверю баг сборки.


Возможные решения:
- Попробуйте обновить quazip на последний
- Попробуйте удалить QT6 (можно вместе с brew) и собрать на QT5: он намного стабильнее
- Или использовать уже собранный релиз https://github.com/noyatsenko/freeLib-mac/releases

**Comment by alldevit** [comment]
Не обратил внимание на доступность релизов, спасибо!
